version: '3.8'

services:
  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data

volumes:
  payment-db-data:
