version: '3.8'

services:
  postgres-payment:
    image: postgres:15
    container_name: postgres-payment
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5433:5432"
    volumes:
      - payment_pg_data:/var/lib/postgresql/data

volumes:
  payment_pg_data:
